import { ITrida } from "../../../models/types";

const A2022: ITrida = {
	title: "4.A - 2021/2022",
	unique: "A21-22",
	domain: "delta-www.cz",
	projects: [
		{
			title: "Fit Grams",
			authorName: "Denis Sháněl",
			subdomain: "a2018shande",
			https: true,
			consultantName: "Adéla Klapal",
		},
		{
			title: "IS - OK Lokomotiva Pardubice",
			authorName: "Martin Zeman",
			subdomain: "a2018zemama",
			https: true,
			consultantName: "Jan Koupil",
		},
		{
			title: "TrackApp",
			authorName: "Matyáš Marek",
			subdomain: "a2018marema",
			https: true,
			consultantName: "Jan Mottl",
		},
		{
			title: "Killer Bee",
			authorName: "Jáchym Vondráček",
			subdomain: "a2018vondja",
			https: true,
			consultantName: "Daniel Václavík",
		},
		{
			title: "3D hra tvořena v Unity",
			authorName: "Dominik Malinovský",
			subdomain: "a2018malido",
			https: true,
			consultantName: "Jan Mottl",
		},
		{
			title: "Most Wanted",
			authorName: "Jiří Juška",
			subdomain: "a2018juskji",
			https: true,
			consultantName: "Richard Brun",
		},
		{
			title: "Inaequalis z.s.",
			authorName: "Viola Pilná",
			subdomain: "a2018pilnvi",
			https: true,
			consultantName: "Daniel Václavík",
		},
		{
			title: "Lodě s možností LAN multiplayeru",
			authorName: "Tomáš Pospíšil",
			subdomain: "a2018pospto",
			https: true,
			consultantName: "Jan Mottl",
		},
		{
			title: "2D Bojová hra",
			authorName: "Daniel Štorek",
			subdomain: "a2018storda",
			https: true,
			consultantName: "Jan Mottl",
		},
		{
			title: "Gamesuit",
			authorName: "Matěj Denis Novotný",
			subdomain: "a2018novoma",
			https: true,
			consultantName: "Daniel Václavík",
		},
		{
			title: "Caffelino",
			authorName: "Markéta Políšenská",
			subdomain: "a2018polima",
			https: true,
			consultantName: "Daniel Václavík",
		},
		{
			title: "Galerie Golfových Hřišť ",
			authorName: "Marek Pavlíček",
			subdomain: "a2018pavlma",
			https: true,
			consultantName: "Vlaďka Janů",
		},
		{
			title: "Climberries",
			authorName: "Štěpán Zamazal",
			subdomain: "a2018zamast",
			https: true,
			consultantName: "Vlaďka Janů",
		},
		{
			title: "Koinoniafy",
			authorName: "Bořek Bartolšic",
			subdomain: "a2018bartbo",
			https: true,
			consultantName: "Vlaďka Janů",
		},
		{
			title: "Betonová Hranice",
			authorName: "Jindřich Knápek",
			subdomain: "a2018knapji",
			https: true,
			consultantName: "Richard Brun",
		},
		{
			title: "Veterinární ordinace Litomyšl",
			authorName: "Dominik Štusák",
			subdomain: "a2018stusdo",
			https: true,
			consultantName: "Veronika Hořeňovská",
		},
		{
			title: "GTS Invest",
			authorName: "Tomáš Korejtko",
			subdomain: "a2018koreto",
			https: true,
			consultantName: "Adéla Klapal",
		},
		{
			title: "Happy Pills",
			authorName: "Matouš Kyncl",
			subdomain: "a2018kyncma",
			https: true,
			consultantName: "Richard Brun",
		},
		{
			title: "Farma Slabý",
			authorName: "Nikola Trpková",
			subdomain: "a2018trpkni",
			https: true,
			consultantName: "Veronika Hořeňovská",
		},
		{
			title: "Chytré domácnosti s.r.o.",
			authorName: "Barbora Beranová",
			subdomain: "a2018beraba",
			https: true,
			consultantName: "Adéla Klapal",
		},
		{
			title: "Dobrá Dýmka",
			authorName: "Sebastian Tamáš",
			subdomain: "a2018tamase",
			https: true,
			consultantName: "Daniel Václavík",
		},
	],
};

export default A2022;
