import { ITrida } from "../../../models/types";

const B1920: ITrida = {
  title: "4.B - 2019/2020",
  unique: "B19-20",
  domain: "delta-studenti.cz",
  projects: [
    {
      title: "Zhodnocení online marketingové strategie společnosti Dům Barev",
      authorName: "Martin Bureš",
      subdomain: "b2016burema",
      keywords: [
        "Dům Barev",
        "analýza potřeb",
        "konkurence",
        "marketing",
        "zákazník",
        "značka",
        "grafika",
        "redesign",
      ],
    },
    {
      title: "Studentská Jízda (Cleach)",
      authorName: "Martin Ďuriš",
      subdomain: "b2016durima",
      keywords: [
        "Backend-as-a-service",
        "GraphQL",
        "Firebase",
        "Serverless",
        "Flutter",
      ],
    },
    {
      title: "Žolíky",
      authorName: "Jirka Falta",
      subdomain: "b2016faltji",
      keywords: [
        "webová aplikace",
        "mobilní aplikace",
        "Windows aplikace",
        "ASP.NET",
        "Flutter",
      ],
    },
    {
      title: "Music video k písničce Repete od skupiny BlackDisease",
      authorName: "Vojta Hečlo",
      subdomain: "b2016heclvo",
      keywords: [
        "Music Video",
        "audioklip",
        "Black Disease",
        "video",
        "hudební klip",
        "Adobe Premiere Pro",
        "Sony Vegas",
        "grafika",
        "písnička",
        "BlackDisease Repete",
      ],
    },
    {
      title:
        "Marketingová komunikace a komunikační mix pro vlastní IT firmu - IT Servis Jiránek",
      authorName: "Vojtěch Jiránek",
      subdomain: "b2016jiravo",
      keywords: [
        "Marketing",
        "marketingová komunikace",
        "komunikační mix",
        "inzerce",
        "IT servis",
        "hardware",
        "software",
        "webové stránky",
      ],
    },
    {
      title: "Marketingová kampaň pro firmu MySmartHouse.cz",
      authorName: "Daniel Jirásek",
      subdomain: "b2016jirada",
      keywords: [
        "Marketing",
        "marketingová strategie",
        "SWOT",
        "SWOT analýza",
        "STDC",
        "STDC framework",
        "cílové skupiny",
        "marketingové persony",
        "webové stránky",
        "grafický design",
      ],
    },
    {
      title: "Sázava GO",
      authorName: "Jan Kollert",
      subdomain: "b2016kollja",
      keywords: [
        "Mobilní aplikace",
        "Pekařství a cukrářství Sázava",
        "Flutter",
        ".NET",
        "Dart",
        "GraphQL",
      ],
    },
    {
      title: "MyBranch",
      authorName: "Karel Koudelka",
      subdomain: "b2016koudka",
      keywords: [
        "Webová aplikace",
        "mobilní aplikace",
        "NextJS",
        "Flutter",
        "GraphQL",
        "interaktivní videa",
      ],
    },
    {
      title: "Marketingová strategie firmy U Dvou krkoviček s.r.o.",
      authorName: "Denisa Lohniská",
      subdomain: "b2016lohnde",
      keywords: [
        "marketing",
        "marketingová strategie",
        "SWOT analýza",
        "STDC Framework",
        "cílové skupiny",
        "PPC reklamy",
        "marketingové persony",
        "grafické návrhy",
      ],
    },
    {
      title:
        "Návrh celé marketingové strategie a brandu společnosti Zooflor Holice",
      authorName: "Robin Mácháček",
      subdomain: "b2016machro",
      keywords: [
        "Marketing",
        "SWOT analýza",
        "STDC framework",
        "cílové skupiny",
        "marketingové persony",
        "grafický návrh",
      ],
    },
    {
      title: "Inteligentní turistický průvodce",
      authorName: "Martin Rohr",
      subdomain: "b2016rohrma",
      keywords: ["Turistický průvodce", "mobilní aplikace", "Flutter", "mapa"],
    },
    {
      title: "???",
      authorName: "Jan Sedlák",
      subdomain: "b2016sedlja",
    },
    {
      title: "Short - The Rapture",
      authorName: "Ondřej Soukup",
      subdomain: "b2016soukon",
      keywords: ["Adobe Premiere Pro", "Scénář", "nástroje", "programy"],
    },
    {
      title:
        "Propagace, marketing a organizace regionálního festivalu dokumentárních filmů o lidských právech JEDEN SVĚT 2019",
      authorName: "Michal Špitálský",
      subdomain: "b2016spitmi",
      keywords: ["Filmový festival", "marketing", "grafika", "sociální sítě"],
    },
    {
      title: "Cvičebnice pro počítačové systémy a sítě",
      authorName: "Michal Štěrba",
      subdomain: "b2016stermi",
      keywords: [
        "Počítačové systémy a sítě",
        "Cisco Packet Tracer",
        "Cvičebnice pss",
        "RIP",
        "ISO/OSI",
        "DHCP",
        "DNS",
      ],
    },
    {
      title:
        "Marketingová strategie pro Chovatelsko-zahrádkářské centrum Holice",
      authorName: "Denisa Štěrbová",
      subdomain: "b2016sterde",
      keywords: [
        "Analýza potřeb",
        "marketingová strategie",
        "cílová skupina",
        "SWOT analýza",
        "PPC reklamy",
        "vizuální identita",
      ],
    },
    {
      title:
        "Propagace, marketing a organizace regionálního festivalu dokumentárních filmů o lidských právech JEDEN SVĚT 2019",
      authorName: "Jakub Tesařík",
      subdomain: "b2016tesaja",
      keywords: ["Filmový festival", "marketing", "grafika", "sociální sítě"],
    },
    {
      title: "Re-design časopisu školy Delta",
      authorName: "Přemysl Tichý",
      subdomain: "b2016tichpr",
      keywords: [
        "Časopis",
        "Redesign",
        "Tvorba časopisu",
        "Vektorová grafika",
        "Rastrová grafika",
        "Grafika",
        "Online Publikace",
        "Vrstvy",
        "Tiskovina",
      ],
    },
    {
      title: "Balíček 3D low poly modelů",
      authorName: "Vojtěch Vázler",
      subdomain: "b2016vazlvo",
      keywords: ["3D model", "Low poly"],
    },
    {
      title:
        "Zhodnocení online marketingové strategie e-shopu OKProdej a návrh nové marketingové strategie",
      authorName: "Filip Zahálka",
      subdomain: "b2016zahafi",
      keywords: [
        "elektronické cigarety",
        "příslušenství",
        "e-cigarety",
        "marketing",
        "mediaplán",
        "analýza potřeb",
      ],
    },
  ],
};

export default B1920;
